<a href="https://colab.research.google.com/github/Chanakarn06/data_viz_2022/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#โหลด data
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# ตารางที่1 ข้อมูลผู้ป่วยปี2020

In [4]:
data1= pd.read_excel('/content/drive/MyDrive/Project_Dashboard2022/confirmed-cases.xlsx')  ## สร้างตัวแปร รับค่าข้อมูลที่อยู่ใน Google drive
data1 ## แสดงข้อมูล

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,2020-01-12,NaT,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,2020-01-17,NaT,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,2020-01-22,NaT,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,2020-01-22,NaT,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,2020-01-24,NaT,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
...,...,...,...,...,...,...,...,...,...,...,...
816984,816985,2021-08-11,2021-08-10,หญิง,8.0,ปี,Thailand,สระแก้ว,อยู่ระหว่างการสอบสวน,สระแก้ว,ตาพระยา
816985,816986,2021-08-11,2021-08-10,ชาย,14.0,ปี,Thailand,สระแก้ว,อยู่ระหว่างการสอบสวน,สระแก้ว,ตาพระยา
816986,816987,2021-08-11,2021-08-10,ชาย,59.0,ปี,Thailand,สระแก้ว,อาชีพเสี่ยง เช่น ทำงานในสถานที่แออัด หรือทำงาน...,สระแก้ว,อรัญประเทศ
816987,816988,2021-08-11,2021-08-10,หญิง,34.0,ปี,Thailand,สระแก้ว,อื่นๆ,กรุงเทพมหานคร,บางขุนเทียน
816988,816989,2021-08-11,2021-08-10,หญิง,19.0,ปี,Thailand,สระแก้ว,อื่นๆ,พระนครศรีอยุธยา,อุทัย

# ตารางที่2 ข้อมูลผู้ป่วยปี2021- 2021เดือน10 วันที่25

In [5]:
data2= pd.read_excel('/content/drive/MyDrive/Project_Dashboard2022/confirmed-cases-since-120864.xlsx')  ## สร้างตัวแปร รับค่าข้อมูลที่อยู่ใน Google drive
data2 ## แสดงข้อมูล

KeyboardInterrupt: ignored

# ตารางที่3 ข้อมูลผู้ป่วยปี2021เดือน10 วันที่26เป็นต้นไป

In [ ]:
data3= pd.read_excel('/content/drive/MyDrive/Project_Dashboard2022/confirmed-cases-since-271064.xlsx')  ## สร้างตัวแปร รับค่าข้อมูลที่อยู่ใน Google drive
data3 ## แสดงข้อมูล

# ตารางที่4 ข้อมูลผู้ป่วยปี2022

In [ ]:
data4= pd.read_excel('/content/drive/MyDrive/Project_Dashboard2022/confirmed-cases-since-280265 (1).xlsx')  ## สร้างตัวแปร รับค่าข้อมูลที่อยู่ใน Google drive
data4 ## แสดงข้อมูล

In [6]:
#โหลด data
import pandas as pd

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
data_co= pd.read_excel('/content/drive/MyDrive/Project_Dashboard2022/citizeninfo_health_20200314 (3).xlsx')  ## สร้างตัวแปร รับค่าข้อมูลที่อยู่ใน Google drive
data_co## แสดงข้อมูล

,รหัสหน่วยงาน,กระทรวง,กรม,หน่วยงาน,หมุดที่ไม่พบความผิดปกติ,ที่อยู่จุดบริการ,ละติจูด,ลองติจูด
0,8899021500001,กระทรวงกลาโหม,กรมแพทย์ทหารบก,โรงพยาบาลค่ายพิชัยดาบหัก,Y,102 หมู่ 8 ต.ท่าเสา อ.เมืองอุตรดิตถ์ จ.อุตรดิต...,17.662624,100.138907
1,8899021200003,กระทรวงกลาโหม,กรมแพทย์ทหารเรือ,โรงพยาบาลสมเด็จพระนางเจ้าสิริกิติ์,N,NaN,NaN,NaN
2,8899021200001,กระทรวงกลาโหม,กรมแพทย์ทหารเรือ,โรงพยาบาลทหารเรือกรุงเทพ,Y,224 ถนนริมทางรถไฟเก่า แขวงบางนา เขตบางนา กรุงเ...,13.670278,100.588009
3,111020400029,กระทรวงกลาโหม,กองทัพบก,กองทัพบก โรงพยาบาลพระมงกุฎเกล้า,Y,แขวงทุ่งพญาไท เขตราชเทวี กรุงเทพมหานคร 10400,13.767327,100.534169
4,113020400030,กระทรวงกลาโหม,กองทัพบก,กองทัพบก โรงพยาบาลอานันทมหิดล,Y,ต.เขาสามยอด อ.เมืองลพบุรี จ.ลพบุรี 15000,14.849659,100.666970
...,...,...,...,...,...,...,...,...
10709,8899417700034,กรุงเทพมหานคร,สำนักอนามัย,ศูนย์บริการสาธารณสุข 21 วัดธาตุทอง,Y,ถนนสุขุมวิท แขวงพระโขนง เขตคลองเตย กรุงเทพมหาน...,13.719146,100.585634
10710,8899417700072,กรุงเทพมหานคร,สำนักอนามัย,ศูนย์บริการสาธารณสุข 59 ทุ่งครุ,Y,บ้านเลขที่ 46 ศูนย์บริการสาธารณสุข 59 ทุ่งครุ ...,13.607237,100.506656
10711,8899417700052,กรุงเทพมหานคร,สำนักอนามัย,ศูนย์บริการสาธารณสุข 39 ราษฎร์บูรณะ,Y,ถนนราษฎร์บูรณะ แขวงราษฎร์บูรณะ เขตราษฎร์บูรณะ ...,13.680928,100.506805
10712,8899417700073,กรุงเทพมหานคร,สำนักอนามัย,ศูนย์บริการสาธารณสุข 60 รสสุคนธ์ มโนชญากรณ์,Y,60 ซอยสรงประภา 11 แขวงดอนเมือง เขตดอนเมือง กรุ...,13.925453,100.580734
10713,8899417700032,กรุงเทพมหานคร,สำนักอนามัย,ศูนย์บริการสาธารณสุข 19 วงศ์สว่าง,Y,วงศ์สว่าง 27 (ซอยสายลม) แขวงวงศ์สว่าง เขตบางซื...,13.827509,100.526282

In [32]:
data_co.dropna()

,รหัสหน่วยงาน,กระทรวง,กรม,หน่วยงาน,หมุดที่ไม่พบความผิดปกติ,ที่อยู่จุดบริการ,ละติจูด,ลองติจูด
0,8899021500001,กระทรวงกลาโหม,กรมแพทย์ทหารบก,โรงพยาบาลค่ายพิชัยดาบหัก,Y,102 หมู่ 8 ต.ท่าเสา อ.เมืองอุตรดิตถ์ จ.อุตรดิต...,17.662624,100.138907
2,8899021200001,กระทรวงกลาโหม,กรมแพทย์ทหารเรือ,โรงพยาบาลทหารเรือกรุงเทพ,Y,224 ถนนริมทางรถไฟเก่า แขวงบางนา เขตบางนา กรุงเ...,13.670278,100.588009
3,111020400029,กระทรวงกลาโหม,กองทัพบก,กองทัพบก โรงพยาบาลพระมงกุฎเกล้า,Y,แขวงทุ่งพญาไท เขตราชเทวี กรุงเทพมหานคร 10400,13.767327,100.534169
4,113020400030,กระทรวงกลาโหม,กองทัพบก,กองทัพบก โรงพยาบาลอานันทมหิดล,Y,ต.เขาสามยอด อ.เมืองลพบุรี จ.ลพบุรี 15000,14.849659,100.666970
5,8899020600012,กระทรวงกลาโหม,กองทัพอากาศ,โรงพยาบาลภูมิพลอดุลยเดช กรมแพทย์ทหารอากาศ,Y,แขวงคลองถนน เขตสายไหม กรุงเทพมหานคร 10220,13.909294,100.618019
...,...,...,...,...,...,...,...,...
10709,8899417700034,กรุงเทพมหานคร,สำนักอนามัย,ศูนย์บริการสาธารณสุข 21 วัดธาตุทอง,Y,ถนนสุขุมวิท แขวงพระโขนง เขตคลองเตย กรุงเทพมหาน...,13.719146,100.585634
10710,8899417700072,กรุงเทพมหานคร,สำนักอนามัย,ศูนย์บริการสาธารณสุข 59 ทุ่งครุ,Y,บ้านเลขที่ 46 ศูนย์บริการสาธารณสุข 59 ทุ่งครุ ...,13.607237,100.506656
10711,8899417700052,กรุงเทพมหานคร,สำนักอนามัย,ศูนย์บริการสาธารณสุข 39 ราษฎร์บูรณะ,Y,ถนนราษฎร์บูรณะ แขวงราษฎร์บูรณะ เขตราษฎร์บูรณะ ...,13.680928,100.506805
10712,8899417700073,กรุงเทพมหานคร,สำนักอนามัย,ศูนย์บริการสาธารณสุข 60 รสสุคนธ์ มโนชญากรณ์,Y,60 ซอยสรงประภา 11 แขวงดอนเมือง เขตดอนเมือง กรุ...,13.925453,100.580734
10713,8899417700032,กรุงเทพมหานคร,สำนักอนามัย,ศูนย์บริการสาธารณสุข 19 วงศ์สว่าง,Y,วงศ์สว่าง 27 (ซอยสายลม) แขวงวงศ์สว่าง เขตบางซื...,13.827509,100.526282

In [10]:
!pip install folium

Requirement already satisfied: folium in /usr/local/lib/python3.7/dist-packages (0.8.3)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from folium) (1.15.0)
Requirement already satisfied: branca>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from folium) (0.4.2)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from folium) (2.23.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from folium) (1.21.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from folium) (2.11.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->folium) (2.0.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->folium) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->folium) (2021.10.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->folium) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->folium) (3.0.4)

In [11]:
import folium # package สำหรับ visualize interactive map

In [14]:
from branca.element import Figure  # จัดการขนาดของ map

In [15]:
fig=Figure(width=550,height=350)

In [30]:
fig2=Figure(width=550,height=350)

mt=folium.Map(location=[16.4743, 102.8222],zoom_start=14)
folium.Marker(location=[16.47447720294497, 102.8230673655105],popup='SC06',tooltip='Science').add_to(mt) # mouse over = tooltip, click = popup

fig2.add_child(mt)